apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-php-app-deployment
  namespace: nginx
  labels:
    app: simple-php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-php-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simple-php-app
    spec:
      restartPolicy: Always
      containers:
      - name: simple-php-app
        image: arinazap/simple-php-app:0.0.1
        ports:
        - name: simple-php-app-http
          containerPort: 8080

