apiVersion: v1
kind: Service
metadata:
  name: simple-php-app-svc
  namespace: simple-php-app
spec:
  selector:
    app: simple-php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
