name: Docker Image Test

on:
  push:
    branches: [ '**' ]
    paths: ['app/**','Dockerfile','.github/workflows/container_image_test.yml']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spring-boot-cc-app:0.0.1

    - name: Run Containerized App
      run: docker run -p 8080:8080 -d --rm --name cc-app spring-boot-cc-app:0.0.1

    - name: Get HTTP response from the App
      run: curl -I http://127.0.0.1:8080